package msme.ir.authmsme.entity;
// Generated Nov 30, 2016 12:43:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * ShiroPermissions generated by hbm2java
 */
@Entity
@Table(name="shiro_permissions"
    ,catalog="authmsme"
)
public class ShiroPermissions  implements java.io.Serializable {


     private String name;
     private String description;
     private Set shiroRoleses = new HashSet(0);

    public ShiroPermissions() {
    }

	
    public ShiroPermissions(String name, String description) {
        this.name = name;
        this.description = description;
    }
    public ShiroPermissions(String name, String description, Set shiroRoleses) {
       this.name = name;
       this.description = description;
       this.shiroRoleses = shiroRoleses;
    }
   
     @Id 

    
    @Column(name="name", unique=true, nullable=false, length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", nullable=false, length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="shiro_roles_permissions", catalog="authmsme", joinColumns = { 
        @JoinColumn(name="permission", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="role", nullable=false, updatable=false) })
    public Set getShiroRoleses() {
        return this.shiroRoleses;
    }
    
    public void setShiroRoleses(Set shiroRoleses) {
        this.shiroRoleses = shiroRoleses;
    }




}


