package msme.ir.authmsme.entity;
// Generated Nov 30, 2016 12:43:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * ShiroPermissions generated by hbm2java
 */
@Entity
@Table(name="shiro_permission"
    ,catalog="authmsme"
)
public class ShiroPermission  implements java.io.Serializable {


     private String name;
     private String description;
     private Set shiroRoles = new HashSet(0);

    public ShiroPermission() {
    }

	
    public ShiroPermission(String name, String description) {
        this.name = name;
        this.description = description;
    }
    public ShiroPermission(String name, String description, Set shiroRoles) {
       this.name = name;
       this.description = description;
       this.shiroRoles = shiroRoles;
    }
   
    @Id
    @Column(name="name", unique=true, nullable=false, length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", nullable=false, length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="shiro_role_permission", catalog="authmsme", joinColumns = { 
        @JoinColumn(name="permission", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="role", nullable=false, updatable=false) })
    public Set getShiroRoles() {
        return this.shiroRoles;
    }
    
    public void setShiroRoles(Set shiroRoles) {
        this.shiroRoles = shiroRoles;
    }




}


