package msme.ir.authmsme.entity;
// Generated Nov 30, 2016 12:43:01 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * ShiroRoles generated by hbm2java
 */
@Entity
@Table(name = "shiro_role", catalog = "authmsme"
)
public class ShiroRole implements java.io.Serializable {

    private String name;
    private String description;
    private Set shiroUsers = new HashSet(0);
    private Set shiroPermissions = new HashSet(0);

    public ShiroRole() {
    }

    public ShiroRole(String name, String description) {
        this.name = name;
        this.description = description;
    }

    public ShiroRole(String name, String description, Set shiroUsers, Set shiroPermissions) {
        this.name = name;
        this.description = description;
        this.shiroUsers = shiroUsers;
        this.shiroPermissions = shiroPermissions;
    }

    @Id
    @Column(name = "name", unique = true, nullable = false, length = 30)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", nullable = false, length = 100)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "shiro_user_role", catalog = "authmsme", joinColumns = {
        @JoinColumn(name = "role", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "user_name", nullable = false, updatable = false)})
    public Set getShiroUsers() {
        return this.shiroUsers;
    }

    public void setShiroUsers(Set shiroUsers) {
        this.shiroUsers = shiroUsers;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "shiro_role_permission", catalog = "authmsme", joinColumns = {
        @JoinColumn(name = "role", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "permission", nullable = false, updatable = false)})
    public Set getShiroPermissions() {
        return this.shiroPermissions;
    }

    public void setShiroPermissions(Set shiroPermissions) {
        this.shiroPermissions = shiroPermissions;
    }

}
